### ISSUE TITLE
验证码识别的准确率变量

### ISSUE THREAD

**Issue by duxiaoyang06** [lpty/tensorflow_train#7]
为什么是变量acc_rate>0.99而不是acc>0.99,acc_rate初始化为0.95，后面每次训练acc大于设定acc_rate的时候acc_rate+0.01，为什么要这么做呢？

**Comment by lpty** [comment]
@duxiaoyang06 都是可以的。这样只是在准确率达到0.99之前保留几份副本，实际准确率很难达到这个程度。
