### ISSUE TITLE
提示找不到poetryRnn模块怎么办

### ISSUE THREAD

**Issue by jayceguo** [lpty/tensorflow_train#8]
ModuleNotFoundError: No module named 'poetryRnn'

**Comment by lpty** [comment]
@SakuraLove 这是路径引用的问题，确认一下工程是不是完整。

**Comment by jayceguo** [comment]
我是直接整个项目下载了下来，然后在子目录里面用命令行python xxx.py运行的

**Comment by jayceguo** [comment]
![tim 20171216154347](https://user-images.githubusercontent.com/20598278/34074201-f40cd716-e277-11e7-9b69-68ebff6c15ff.png)

**Comment by jayceguo** [comment]
`PS D:\Python ML学习\tensorflow_tutorial-master\poetryRnn> LS


    目录: D:\Python ML学习\tensorflow_tutorial-master\poetryRnn


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2017/10/9      8:36           1927 poetry.py
-a----        2017/10/9      8:36        2683016 poetry.txt
-a----        2017/10/9      8:36            155 poetry_gen.py
-a----        2017/10/9      8:36           7284 poetry_model.py
-a----        2017/10/9      8:36            130 poetry_train.py
-a----        2017/10/9      8:36            223 README.md
-a----        2017/10/9      8:36              0 __init__.py`

**Comment by lpty** [comment]
@SakuraLove 嗯 这份代码只是一个demo 没考虑一些兼容的东西 你手动修改import的路径就可以了

**Comment by jayceguo** [comment]
话说头像生成那个可以生成大一点的图片吗

**Comment by lpty** [comment]
@SakuraLove 可以 调整一下图片的配置大小就行了
